### ISSUE TITLE
Bump eslint from 8.57.0 to 9.7.0

### ISSUE THREAD

**Issue by BlueCutOfficial** [DazzlingFugu/ember-reading-time#206]
The Dependabot PR failed because this is a major version that changes entirely the config format for ESLint. 
We should do this upgrade ourselves following the migration guide: https://eslint.org/docs/latest/use/configure/migration-guide

**Comment by BlueCutOfficial** [comment]
After using the codemod to generate `eslint.config.mjs`, I ran into the following error when running the linter:
```
Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace
```
This error comes from the [globals](https://www.npmjs.com/package/globals) package itself. We rely on a version that literally contains the said typo. The latest version (15.8.0) [has been fixed](https://github.com/sindresorhus/globals/blob/v15.8.0/globals.json#L61). Using yarn `resolutions` to force the usage of a fixed version solve the linter issue.

**Comment by BlueCutOfficial** [comment]
The next problem is:
```
TypeError: context.getAncestors is not a function
Occurred while linting /Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-reading-time/.stylelintrc.js
Rule: "ember/require-return-from-computed"
  at onCodePathStart (/Users/marine/Desktop/Repos/opensource/dazzlingfugu/ember-reading-time/node_modules/eslint-plugin-ember/lib/rules/require-return-from-computed.js:70:16)
```

Unfortunately, this issue is currently blocked by [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember) not supporting every aspect of ESLint 9. The specific problem above should be fixed with [eslint-plugin-ember#2153](https://github.com/ember-cli/eslint-plugin-ember/pull/2153) but it hasn't been released yet.

**Comment by LucasHill** [comment]
Just a note that my fix wasn't complete, but it does open up using a workaround to getting the ember plugin running in v9.
https://github.com/ember-cli/eslint-plugin-ember/issues/2136#issuecomment-2189878620

**Comment by MrChocolatine** [comment]
Upgrade being done in #246 .
